Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest:8443, host:443, auto_correct: false 
  config.vm.network "forwarded_port", guest:53, host:53, auto_correct: false 
  config.vm.network "forwarded_port", guest:67, host:67, auto_correct: false 
  config.vm.network "forwarded_port", guest:8080, host:80, auto_correct: false 
  config.vm.network "forwarded_port", guest:5054, host:5054, auto_correct: false 
config.vm.provider "virtualbox" do |vb|
  vb.memory = "512"  
end
config.vm.provision "shell", inline: <<-SHELL
 #Get Docker Image

sudo apt-get update

sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

#Install Docker

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io -y

SHELL
end